Feature: Obter Board da Ação

    # CORREÇÃO 1: Use "Scenario Outline" para indicar que há variáveis (<...>)
    Scenario Outline: Buscar quadro com IDs variáveis
        Given que possuo credenciais válidas do Trello
        And que tenho um board e um card criados para gerar uma ação
        # O pytest vai substituir <id_acao> pelo valor da tabela
        When eu busco o board usando o ID da ação "<id_acao>"
        Then o status da resposta deve ser <status_esperado>

        # CORREÇÃO 2: Use "Examples" (Plural)
        Examples:
        | id_acao         | status_esperado |
        | AUTOGENERATED   | 200             |
        | id_invalido_xyz | 400             |