import pytest
import requests
import os
import time 
from pytest_bdd import scenarios, given, when, then, parsers
from dotenv import load_dotenv

load_dotenv()
BASE = os.getenv("TRELLO_BASE_URL")
AUTH = {"key": os.getenv("TRELLO_KEY"), "token": os.getenv("TRELLO_TOKEN")}

# Carrega o arquivo .feature correto
scenarios('get_the_board_for_an_action.feature')

@pytest.fixture
def context():
    """Dicionário para passar dados de um passo para outro."""
    return {}

@pytest.fixture
def setup_action_data():
    """
    Cria um cenário real no Trello para termos um ID válido:
    Cria Board -> Cria Lista -> Cria Card (isso gera uma Action).
    """
    r_board = requests.post(f"{BASE}/boards", params={**AUTH, "name": "Board Para Action Test"})
    board_id = r_board.json()["id"]
    
    r_list = requests.post(f"{BASE}/lists", params={**AUTH, "name": "Lista", "idBoard": board_id})
    list_id = r_list.json()["id"]

    r_card = requests.post(f"{BASE}/cards", params={**AUTH, "name": "Card Teste", "idList": list_id})
    card_id = r_card.json()["id"]

    time.sleep(1)

    r_actions = requests.get(
        f"{BASE}/cards/{card_id}/actions", 
        params={**AUTH, "filter": "all"}
    )
    
    try:
        action_id = r_actions.json()[0]["id"]
    except IndexError:
        # Fallback de segurança
        requests.delete(f"{BASE}/boards/{board_id}", params=AUTH)
        pytest.fail(f"A API não retornou ações para o card. Resposta: {r_actions.json()}")

    data = {"board_id": board_id, "action_id": action_id}
    
    yield data 

    # del o board
    requests.delete(f"{BASE}/boards/{board_id}", params=AUTH)

# TC: Obter o board associado a uma ação via ID da ação

@given("que possuo credenciais válidas do Trello")
def credentials_check():
    assert AUTH["key"] and AUTH["token"]

@given("que tenho um board e um card criados para gerar uma ação")
def setup_environment(setup_action_data, context):
    # Guardamos o ID real gerado no contexto
    context["real_action_id"] = setup_action_data["action_id"]
    context["expected_board_id"] = setup_action_data["board_id"]

@when(parsers.parse('eu busco o board usando o ID da ação "{id_acao}"'))
def get_board_request(context, id_acao):
    # LÓGICA DO AUTOGENERATED
    if id_acao == "AUTOGENERATED":
        id_para_usar = context["real_action_id"]
    else:
        id_para_usar = id_acao
    
    # Faz GET
    response = requests.get(f"{BASE}/actions/{id_para_usar}/board", params=AUTH)
    context["response"] = response

@then(parsers.parse('o status da resposta deve ser {status_esperado:d}'))
def check_status(context, status_esperado):
    assert context["response"].status_code == status_esperado

    # Validação extra 
    if status_esperado == 200:
        data = context["response"].json()
        assert data["id"] == context["expected_board_id"]